server:
  port: 8181 #服务端口
  servlet:
    context-path: /rocketmq-producer

spring:
  application:
    name: rocketmq-producer #指定服务名
rocketmq:
  # mq地址
  nameServer: 58.221.72.174:9876


  # 生产者组
  producer:
    group: demo-producer-group
